server:
  port: 8082

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/
    fetch-registry: true
    register-with-eureka: true

spring:
  application:
    name: spring-boot-microservices
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  jmx:
    enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/spring_boot_microservices?allowPublicKeyRetrieval=true&sslMode=DISABLED
    username: root
    password: 1234